import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import WalletConnect from '@/components/WalletConnect'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Code-C --> Web3Together',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletConnect>
          {children}
        </WalletConnect>
      </body>
    </html>
  )
}
